#request
uint8 payload_index #see enum class PayloadIndex in common_type.h
uint8 multiplier #Data struct of tap zoom multiplier used by user. Limit: 1~5
float32 x  # range from 0~1, top left corner is origin point
float32 y  # range from 0~1, top left corner is origin point
---
#response
bool result