Header header
# ts is the time it takes to achieve the desired angle,
# so the shorter the time, the faster the gimbal rotates.

#request
bool is_reset

uint8 payload_index

# rotation cooradiration
# 0 = execute angle command based on the previously set reference point
# 1 = execute angle command based on the current point
uint8 rotationMode

# pitch angle in degree, unit : deg
float32 pitch

# roll angle in degree, unit : deg
float32 roll

# yaw angle in degree, unit : deg
float32 yaw

#execution time, unit : second
float64 time

---
#response
bool result
