#request
bool enable
---
#response
bool result
uint32 timeStamp
uint8 deviceIndex         # When the error code is related to camera or gimbal device,
                          # it will tell you which device it is.
HMSPushInfo[] errList     # error code list in each pushing